SHELL=/bin/bash

mat_mul_example:
        rm -rf timeline_00.json
        rm -rf run_00.log
        #LOG_LEVEL=3 python3 mat_mul_example.py &> mat_mul_example.log
        python3 mat_mul_example.py &> mat_mul_example.log

mat_mul_add_example:
        rm -rf timeline_01.json
        rm -rf run_01.log
        #LOG_LEVEL=3 python3 mat_mul_add_example.py &> mat_mul_add_example.log
        python3 mat_mul_add_example.py &> mat_mul_add_example.log
