SHELL=/bin/bash

mat_mul_example:
	rm -rf mat_mul_example.json
	rm -rf mat_mul_example.log
	#LOG_LEVEL=3 python3 mat_mul_example.py &> mat_mul_example.log
	python3 mat_mul_example.py &> mat_mul_example.log

mat_mul_add_example:
	rm -rf mat_mul_add_example.json
	rm -rf mat_mul_add_example.log
	#LOG_LEVEL=3 python3 mat_mul_add_example.py &> mat_mul_add_example.log
	python3 mat_mul_add_example.py &> mat_mul_add_example.log
